networks:
  bridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.0.0.0/24
          gateway: 192.0.0.1
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      bridge:
        ipv4_address: 192.0.0.2
    ports:
      - 3330:3330
    volumes:
      - ./Data/Databases/MySQL:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
    networks:
      bridge:
        ipv4_address: 192.0.0.3
    ports:
      - 6330:6330
    volumes:
      - ./Data/Databases/Redis:/data
  gateserver:
    build: .
    image: hk4e/ubuntu
    container_name: gateserver
    restart: unless-stopped
    depends_on:
      mysql: { condition: service_healthy }
      redis: { condition: service_healthy }
      gameserver: { condition: service_started }
      dispatch: { condition: service_started }
      pathfindingserver: { condition: service_started }
      tothemoonserver: { condition: service_started }
    networks:
      bridge:
        ipv4_address: 192.0.0.11
    ports:
      - 18101:18101
      - 18101:18101/udp
    volumes:
      - ./Bin/lib/libasan.so.5:/lib/libasan.so.5:ro
      - ./Bin/lib/libgcc_s.so.1:/lib/libgcc_s.so.1:ro
      - ./Bin/lib/libstdc++.so.6:/lib/libstdc++.so.6:ro
      - ./Bin/gateserver/gateserver:/app/gateserver:ro
      - ./Data/data:/data:ro
      - ./Config/gateserver.xml:/app/conf/gateserver.xml
      - ./Log:/app/log
    command: ./gateserver -i 1.1.1.1
  gameserver:
    build: .
    image: hk4e/ubuntu
    container_name: gameserver
    restart: unless-stopped
    depends_on:
      mysql: { condition: service_healthy }
      redis: { condition: service_healthy }
      nodeserver: { condition: service_started }
    networks:
      bridge:
        ipv4_address: 192.0.0.12
    expose:
      - 18201
    volumes:
      - ./Bin/lib/libasan.so.5:/lib/libasan.so.5:ro
      - ./Bin/lib/libgcc_s.so.1:/lib/libgcc_s.so.1:ro
      - ./Bin/lib/libstdc++.so.6:/lib/libstdc++.so.6:ro
      - ./Bin/gameserver/gameserver:/app/gameserver:ro
      - ./Data/data:/data:ro
      - ./Config/gameserver.xml:/app/conf/gameserver.xml
      - ./Data/data/json:/data/json:ro
      - ./Data/data/lua:/data/lua:ro
      - ./Data/data/txt:/data/txt:ro
      - ./Data/data/xml:/data/xml:ro
      - ./Log:/app/log
      - ./Data/res:/res
    command: ./gameserver -i 1.2.1.1
  nodeserver:
    build: .
    image: hk4e/ubuntu
    container_name: nodeserver
    restart: unless-stopped
    depends_on:
      mysql: { condition: service_healthy }
      redis: { condition: service_healthy }
    networks:
      bridge:
        ipv4_address: 192.0.0.13
    expose:
      - 18301
    volumes:
      - ./Bin/lib/libasan.so.5:/lib/libasan.so.5:ro
      - ./Bin/lib/libgcc_s.so.1:/lib/libgcc_s.so.1:ro
      - ./Bin/lib/libstdc++.so.6:/lib/libstdc++.so.6:ro
      - ./Bin/nodeserver/nodeserver:/app/nodeserver:ro
      - ./Data/data:/data:ro
      - ./Config/nodeserver.xml:/app/conf/nodeserver.xml
      - ./Log:/app/log
    command: ./nodeserver -i 1.3.1.1
  dbgate:
    build: .
    image: hk4e/ubuntu
    container_name: dbgate
    restart: unless-stopped
    depends_on:
      mysql: { condition: service_healthy }
      redis: { condition: service_healthy }
      nodeserver: { condition: service_started }
    networks:
      bridge:
        ipv4_address: 192.0.0.14
    volumes:
      - ./Bin/lib/libasan.so.5:/lib/libasan.so.5:ro
      - ./Bin/lib/libgcc_s.so.1:/lib/libgcc_s.so.1:ro
      - ./Bin/lib/libstdc++.so.6:/lib/libstdc++.so.6:ro
      - ./Bin/dbgate/dbgate:/app/dbgate:ro
      - ./Data/data:/data:ro
      - ./Config/dbgate.xml:/app/conf/dbgate.xml
      - ./Log:/app/log
    command: ./dbgate -i 1.4.1.1
  dispatch:
    build: .
    image: hk4e/ubuntu
    container_name: dispatch
    restart: unless-stopped
    depends_on:
      mysql: { condition: service_healthy }
      redis: { condition: service_healthy }
    networks:
      bridge:
        ipv4_address: 192.0.0.15
    ports:
      - 18401:18401
      - 18421:18421
    volumes:
      - ./Bin/lib/libasan.so.5:/lib/libasan.so.5:ro
      - ./Bin/lib/libgcc_s.so.1:/lib/libgcc_s.so.1:ro
      - ./Bin/lib/libstdc++.so.6:/lib/libstdc++.so.6:ro
      - ./Bin/dispatch/dispatch:/app/dispatch:ro
      - ./Data/data:/data:ro
      - ./Config/dispatch.xml:/app/conf/dispatch.xml
      - ./Log:/app/log
    command: ./dispatch -i 1.5.1.1
  muipserver:
    build: .
    image: hk4e/ubuntu
    container_name: muipserver
    restart: unless-stopped
    depends_on:
      mysql: { condition: service_healthy }
      redis: { condition: service_healthy }
      nodeserver: { condition: service_started }
    networks:
      bridge:
        ipv4_address: 192.0.0.16
    ports:
      - 18541:18541
    volumes:
      - ./Bin/lib/libasan.so.5:/lib/libasan.so.5:ro
      - ./Bin/lib/libgcc_s.so.1:/lib/libgcc_s.so.1:ro
      - ./Bin/lib/libstdc++.so.6:/lib/libstdc++.so.6:ro
      - ./Bin/muipserver/muipserver:/app/muipserver:ro
      - ./Data/data:/data:ro
      - ./Config/muipserver.xml:/app/conf/muipserver.xml
      - ./Data/data/json:/data/json:ro
      - ./Data/data/lua:/data/lua:ro
      - ./Data/data/txt:/data/txt:ro
      - ./Data/data/xml:/data/xml:ro
      - ./Log:/app/log
      - ./Data/res:/res
    command: ./muipserver -i 1.6.1.1
  multiserver:
    build: .
    image: hk4e/ubuntu
    container_name: multiserver
    restart: unless-stopped
    depends_on:
      mysql: { condition: service_healthy }
      redis: { condition: service_healthy }
      nodeserver: { condition: service_started }
    networks:
      bridge:
        ipv4_address: 192.0.0.17
    volumes:
      - ./Bin/lib/libasan.so.5:/lib/libasan.so.5:ro
      - ./Bin/lib/libgcc_s.so.1:/lib/libgcc_s.so.1:ro
      - ./Bin/lib/libstdc++.so.6:/lib/libstdc++.so.6:ro
      - ./Bin/multiserver/multiserver:/app/multiserver:ro
      - ./Data/data:/data:ro
      - ./Config/multiserver.xml:/app/conf/multiserver.xml
      - ./Data/data/json:/data/json:ro
      - ./Data/data/lua:/data/lua:ro
      - ./Data/data/txt:/data/txt:ro
      - ./Data/data/xml:/data/xml:ro
      - ./Log:/app/log
      - ./Data/res:/res
    command: ./multiserver -i 1.7.1.1
    pathfindingserver:
     build: .
     image: hk4e/ubuntu
     container_name: pathfindingserver
     restart: unless-stopped
     depends_on:
       mysql: { condition: service_healthy }
       redis: { condition: service_healthy }
     networks:
       bridge:
         ipv4_address: 192.0.0.18
     expose:
       - 18551
     volumes:
       - ./Bin/lib/libasan.so.5:/lib/libasan.so.5:ro
       - ./Bin/lib/libgcc_s.so.1:/lib/libgcc_s.so.1:ro
       - ./Bin/lib/libstdc++.so.6:/lib/libstdc++.so.6:ro
       - ./Bin/pathfindingserver/pathfindingserver:/app/pathfindingserver:ro
       - ./Data/data:/data:ro
       - ./Config/pathfindingserver.xml:/app/conf/pathfindingserver.xml
       - ./Log:/app/log
       - ./Data/res:/res
     command: ./pathfindingserver -i 1.8.1.1
  oaserver:
    build: .
    image: hk4e/ubuntu
    container_name: oaserver
    restart: unless-stopped
    depends_on:
      mysql: { condition: service_healthy }
      redis: { condition: service_healthy }
      nodeserver: { condition: service_started }
    networks:
      bridge:
        ipv4_address: 192.0.0.19
    ports:
      - 18601:18601
    volumes:
      - ./Bin/lib/libasan.so.5:/lib/libasan.so.5:ro
      - ./Bin/lib/libgcc_s.so.1:/lib/libgcc_s.so.1:ro
      - ./Bin/lib/libstdc++.so.6:/lib/libstdc++.so.6:ro
      - ./Bin/oaserver/oaserver:/app/oaserver:ro
      - ./Data/data:/data:ro
      - ./Config/oaserver.xml:/app/conf/oaserver.xml
      - ./Data/data/json:/data/json:ro
      - ./Data/data/lua:/data/lua:ro
      - ./Data/data/txt:/data/txt:ro
      - ./Data/data/xml:/data/xml:ro
      - ./Log:/app/log
      - ./Data/res:/res
    command: ./oaserver -i 1.9.1.1
   tothemoonserver:
     build: .
     image: hk4e/ubuntu
     container_name: tothemoonserver
     restart: unless-stopped
     depends_on:
       mysql: { condition: service_healthy }
       redis: { condition: service_healthy }
     networks:
       bridge:
         ipv4_address: 192.0.0.20
     expose:
       - 18701
     volumes:
       - ./Bin/lib/libasan.so.5:/lib/libasan.so.5:ro
       - ./Bin/lib/libgcc_s.so.1:/lib/libgcc_s.so.1:ro
       - ./Bin/lib/libstdc++.so.6:/lib/libstdc++.so.6:ro
       - ./Bin/tothemoonserver/tothemoonserver:/app/tothemoonserver:ro
       - ./Data/data:/data:ro
       - ./Config/tothemoonserver.xml:/app/conf/tothemoonserver.xml
       - ./Log:/app/log
       - ./Data/res:/res
     command: ./tothemoonserver -i 1.10.1.1
  sdkserver:
    build: .
    image: hk4e/ubuntu
    container_name: sdkserver
    restart: unless-stopped
    networks:
      bridge:
        ipv4_address: 192.0.0.21
    ports:
      - 2300:2330
    volumes:
      - ./Bin/sdkserver/sdkserver:/app/emu:ro
      - ./Config/config.yaml:/app/config.yaml
      - ./Data/sdkdata:/app/data
      - ./Log:/app/log
    command: ./sdkserver