version: "3.8"
networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/8
          gateway: 10.0.0.1
services:
  redis:
    image: redis:7.0
    container_name: Redis
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
    networks:
      network:
        ipv4_address: 10.0.0.3
    ports:
      - 3340:6330
    volumes:
      - ./Database/Redis:/data
    command: --requirepass "5bad6ba4-b6ec-460f-abaf-801d7396c9c4" --databases "168"